service: node-serverless-techinical-challange

provider:
  name: aws
  runtime: nodejs14.x

package:
  excludeDevDependencies: true
  individually: true

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hi
          method: get
