service: node-serverless-techinical-challange

provider:
  name: aws
  runtime: nodejs14.x

package:
  excludeDevDependencies: true
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  hello:
    handler: hello/handler.hello
    events:
      - http:
          path: /hello
          method: get
  get-divisors-and-prime-numbers:
    handler: get-divisors-and-prime-numbers/handler.runner
    events:
      - http:
          path: /get-divisors-and-prime-numbers
          method: post
